export const inputControlsArr=[
  {
    name:'ques',
    lbl:'Question',
    tag:'textarea',
    val:" ",
    errorMsg:'',
    isShowErrorMsg:false
  },
  {
    name:'opt1',
    lbl:'option1',
    tag:'input',
    type:'text',
    val:'',
    errorMsg:'',
    isShowErrorMsg:false
  },
  {
    name:'opt2',
    lbl:'option2',
    tag:'input',
    type:'text',
    val:'',
    errorMsg:'',
    isShowErrorMsg:false
  },
  {
    name:'opt3',
    lbl:'option3',
    tag:'input',
    type:'text',
    val:'',
    errorMsg:'',
    isShowErrorMsg:false
  },
  {
    name:'opt4',
    lbl:'option4',
    tag:'input',
    type:'text',
    val:'',
    errorMsg:'',
    isShowErrorMsg:false
  },
  {
    name:'type',
    lbl:'Type',
    tag:'input',
    type:'radio',
    options:['Single','Multiple'],
    values:['S','M'],
    val:'',
    errorMsg:'',
    isShowErrorMsg:false
  },
  {
    name:'ans',
    lbl:'Answer',
    tag:'select',
    options:['A','B','C','D'],
    val:'',
    errorMsg:'',
    isShowErrorMsg:false
  }
]